// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxftogivsyunbkffupdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4ZnRvZ2l2c3l1bmJrZmZ1cGRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MTQyMTgsImV4cCI6MjA3MzM5MDIxOH0.0qf78AGfm9-vS6y-k96PKypr3wfqmGqXqNDHe2BqEO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});